package com.test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;

/**
 * Main entry point for test-query-authcontext-repo-param.
 * Generated by dsl-springboot-generator.
 */
@SpringBootApplication
@EnableJpaAuditing
@EnableFeignClients
public class TestQueryAuthcontextRepoParamApplication {

    public static void main(String[] args) {
        SpringApplication.run(TestQueryAuthcontextRepoParamApplication.class, args);
    }
}
