-- derived_from: bc.<bc>.projections[*] (persistent: true)
-- Persistent local read models materialized from upstream events.
-- Auto-generated by dsl-springboot-generator.


-- ── orders.LocalProductView ───────────────────────────────────────
-- source: catalog.ProductActivated  upsert: lastWriteWins
CREATE TABLE IF NOT EXISTS proj_local_product_view (
    product_id uuid NOT NULL PRIMARY KEY,
    product_name text NOT NULL,
    price numeric(10, 2) NOT NULL,
    last_updated_at TIMESTAMP NOT NULL
);


