package com.test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;
import org.springframework.scheduling.annotation.EnableScheduling;

/**
 * Main entry point for test-saga-kafka-system.
 * Generated by dsl-springboot-generator.
 */
@SpringBootApplication
@EnableJpaAuditing
@EnableFeignClients
@EnableScheduling
public class TestSagaKafkaSystemApplication {

    public static void main(String[] args) {
        SpringApplication.run(TestSagaKafkaSystemApplication.class, args);
    }
}
