-- derived_from: bc.<bc>.projections[*] (persistent: true)
-- Persistent local read models materialized from upstream events.
-- Auto-generated by dsl-springboot-generator.


-- ── booking.DailyCapacity ───────────────────────────────────────
-- source: calendar.SlotCapacityPublished  upsert: lastWriteWins
CREATE TABLE IF NOT EXISTS proj_daily_capacity (
    date date NOT NULL PRIMARY KEY,
    total_slots integer NOT NULL,
    booked_slots integer NOT NULL,
    last_updated_at TIMESTAMP NOT NULL
);


