package com.test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;

/**
 * Main entry point for test-proj-system.
 * Generated by dsl-springboot-generator.
 */
@SpringBootApplication
@EnableJpaAuditing
@EnableFeignClients
public class TestProjSystemApplication {

    public static void main(String[] args) {
        SpringApplication.run(TestProjSystemApplication.class, args);
    }
}
