-- derived_from: bc.<bc>.projections[*] (persistent: true)
-- Persistent local read models materialized from upstream events.
-- Auto-generated by dsl-springboot-generator.


-- ── inventory.ProductStock ───────────────────────────────────────
-- source: catalog.StockInitialized  upsert: versionGuarded
CREATE TABLE IF NOT EXISTS proj_product_stock (
    product_id uuid NOT NULL PRIMARY KEY,
    quantity integer NOT NULL,
    reserved_quantity integer NOT NULL,
    unit_cost numeric(10, 4) NOT NULL,
    last_updated_at TIMESTAMP NOT NULL
);


