package com.test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;
import org.springframework.scheduling.annotation.EnableScheduling;

/**
 * Main entry point for test-event-system.
 * Generated by dsl-springboot-generator.
 */
@SpringBootApplication
@EnableJpaAuditing
@EnableFeignClients
@EnableScheduling
public class TestEventSystemApplication {

    public static void main(String[] args) {
        SpringApplication.run(TestEventSystemApplication.class, args);
    }
}
