-- derived_from: bc.<bc>.projections[*] (persistent: true)
-- Persistent local read models materialized from upstream events.
-- Auto-generated by dsl-springboot-generator.


-- ── dashboard.ServiceMetrics ───────────────────────────────────────
-- source: monitoring.ServiceCheckCompleted  upsert: lastWriteWins
CREATE TABLE IF NOT EXISTS proj_service_metrics (
    service_id uuid NOT NULL PRIMARY KEY,
    average_latency interval NOT NULL,
    dashboard_url text,
    score numeric(5, 2) NOT NULL,
    last_updated_at TIMESTAMP NOT NULL
);


